coverage_service: cobertura_xml
xcodeproj: DarkSkySwift.xcodeproj
workspace: DarkSkySwift.xcworkspace
scheme: DarkSkySwift-iOS
configuration: Release
source_directory: Sources
output_directory: reports
ignore:
  - scripts/*
  - Tests/*
  - Carthage/*
