language: objective-c
os: osx
osx_image: xcode8.3
xcode_project: DarkSkySwift.xcodeproj
xcode_scheme: DarkSkySwift-iOS
xcode_sdk: iphonesimulator10.3

env:
  global:
    - FRAMEWORK_NAME=DarkSkySwift

before_install:
  - rvm use $RVM_RUBY_VERSION
  - brew update
  - brew outdated carthage || brew upgrade carthage

install:
  - bundle install --without=documentation --path ../travis_bundle_dir

before_script:
  - carthage bootstrap
  - bundle exec danger

matrix:
  include:
    - osx_image: xcode8.3
      env: SCHEME="macOS"  SDK="macosx10.12"          DESTINATION="arch=x86_64"
    - osx_image: xcode8.3
      env: SCHEME="iOS"    SDK="iphonesimulator10.3"  DESTINATION="OS=10.3,name=iPhone 6S Plus"
    - osx_image: xcode8.3
      env: SCHEME="tvOS"   SDK="appletvsimulator10.3"  DESTINATION="OS=10.3,name=Apple TV 1080p"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - travis_retry xcodebuild
    -project "$FRAMEWORK_NAME.xcodeproj"
    -scheme "$FRAMEWORK_NAME-$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    test | xcpretty -f `xcpretty-travis-formatter`

# before_deploy:
#   - carthage build --no-skip-current
#   - carthage archive $FRAMEWORK_NAME

after_success:
    - slather
    - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode
